name: PR Checks

# Trigger conditions for the workflow
on:
  push:
    branches: [ dev ]  # Runs on pushes to dev branch
  pull_request:       # Runs on all pull requests

# Concurrency settings to prevent multiple simultaneous workflow runs
concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true  # Cancels previous runs if a new one is triggered

permissions:
  contents: write

jobs:
  pr_checks:
    name: PR Checks
    uses: openMF/mifos-mobile-github-actions/.github/workflows/pr-check.yaml@main
    secrets: inherit
    with:
      android_package_name: 'mifospay-android'
      desktop_package_name: 'mifospay-desktop'