# Workflow to automatically create weekly version tags and trigger beta releases
# This workflow runs every Sunday at 4:00 AM UTC and can also be triggered manually

name: Tag Weekly Release

on:
  # Allow manual triggering of the workflow
  workflow_dispatch:
  # Schedule the workflow to run weekly
  schedule:
    # Runs at 04:00 UTC every Sunday
    # Cron syntax: minute hour day-of-month month day-of-week
    - cron: '0 4 */2 * 0'

concurrency:
  group: "weekly-release"
  cancel-in-progress: false

jobs:
  tag:
    name: Tag Weekly Release
    uses: openMF/mifos-mobile-github-actions/.github/workflows/tag-weekly-release.yaml@main
    secrets: inherit
    with:
      target_branch: 'dev'